name: Docker Image
on:
  schedule:
    - cron:  '* 1 * * *'
  create:
  push:
    branches:
      - v1.4.0
jobs:
  docker:
    name: Docker publishing
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Apt update
        run: sudo apt-get update
      - name: Install OpenCL
        run: sudo apt-get install mesa-opencl-icd ocl-icd-opencl-dev
      - name: Check out code
        uses: actions/checkout@v1
      - name: Build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./run.sh
